version: '3.7'

services:
  contracts:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - dev.env
    volumes:
      - ./volumes/out:/usr/src/app/out:wo
      - type: bind
        target: /usr/src/app/deployments.txt
        source: ./volumes/deployments.txt
      - ./volumes/broadcast:/usr/src/app/broadcast:wo
    ports:
      - "8545:8545"
    networks:
      - mainnet

networks:
  mainnet:
    name: mainnet
    external: true
