version: '3.7'

services:
  contracts:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - ADDR_A1=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
      - PVK_A1=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - RPC_PORT=8545
    volumes:
      - ./volumes/out:/usr/src/app/out:wo
      - type: bind
        target: /usr/src/app/deployments.txt
        source: ./volumes/deployments.txt
      - ./volumes/broadcast:/usr/src/app/broadcast:wo
    ports:
      - "8545:8545"
    networks:
      - mainnet

networks:
  mainnet:
    name: mainnet
    external: true
