version: '3.8'

services:
  contracts:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./volumes/out:/usr/src/app/out:wo
      - type: bind
        target: /usr/src/app/deployments.txt
        source: ./volumes/deployments.txt
      - ./volumes/broadcast:/usr/src/app/broadcast:wo
    ports:
      - "8545:8545"
    networks:
      - mumbai

networks:
  mumbai:
    name: mumbai
    external: true
