[profile.default]
solc-version = "0.8.21"
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
fs_permissions = [{ access = "read-write", path = "test/testData/LRfuzzDataOut.csv"}, { access = "read-write", path = "deployments.txt"}, { access = "read-write", path = "script/DeploymentAddresses.sol"}]
optimizier_runs=10_000

[rpc_endpoints]
goerli = "${GOERLI_ALCHEMY}"
mumbai="${MUMBAI_ALCHEMY}"

[fuzz]
runs = 1000

[profile.ci]
verbosity = 2
fuzz.runs = 0
