/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface HubRegistryInterface extends utils.Interface {
  functions: {
    "autIDAddr()": FunctionFragment;
    "deployHub(uint256,string,uint256)": FunctionFragment;
    "getHubByDeployer(address)": FunctionFragment;
    "getHubs()": FunctionFragment;
    "getTrustedForwarder()": FunctionFragment;
    "isTrustedForwarder(address)": FunctionFragment;
    "hubs(uint256)": FunctionFragment;
    "pluginRegistry()": FunctionFragment;
    "setAllowListAddress(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "autIDAddr"
      | "deployHub"
      | "getHubByDeployer"
      | "getHubs"
      | "getTrustedForwarder"
      | "isTrustedForwarder"
      | "hubs"
      | "pluginRegistry"
      | "setAllowListAddress"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "autIDAddr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deployHub",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHubByDeployer",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getHubs", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTrustedForwarder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "hubs", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "pluginRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowListAddress",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "autIDAddr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deployHub", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHubByDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getHubs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hubs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pluginRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowListAddress",
    data: BytesLike
  ): Result;

  events: {
    "HubDeployed(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "HubDeployed"): EventFragment;
}

export interface HubDeployedEventObject {
  hub: string;
}
export type HubDeployedEvent = TypedEvent<[string], HubDeployedEventObject>;

export type HubDeployedEventFilter = TypedEventFilter<HubDeployedEvent>;

export interface HubRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: HubRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    autIDAddr(overrides?: CallOverrides): Promise<[string]>;

    deployHub(
      market: BigNumberish,
      metadata: string,
      commitment: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getHubByDeployer(
      deployer: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getHubs(overrides?: CallOverrides): Promise<[string[]]>;

    getTrustedForwarder(
      overrides?: CallOverrides
    ): Promise<[string] & { forwarder: string }>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    hubs(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    pluginRegistry(overrides?: CallOverrides): Promise<[string]>;

    setAllowListAddress(
      allowListAddress_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  autIDAddr(overrides?: CallOverrides): Promise<string>;

  deployHub(
    market: BigNumberish,
    metadata: string,
    commitment: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getHubByDeployer(
    deployer: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getHubs(overrides?: CallOverrides): Promise<string[]>;

  getTrustedForwarder(overrides?: CallOverrides): Promise<string>;

  isTrustedForwarder(
    forwarder: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  hubs(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  pluginRegistry(overrides?: CallOverrides): Promise<string>;

  setAllowListAddress(
    allowListAddress_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    autIDAddr(overrides?: CallOverrides): Promise<string>;

    deployHub(
      market: BigNumberish,
      metadata: string,
      commitment: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getHubByDeployer(
      deployer: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getHubs(overrides?: CallOverrides): Promise<string[]>;

    getTrustedForwarder(overrides?: CallOverrides): Promise<string>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    hubs(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    pluginRegistry(overrides?: CallOverrides): Promise<string>;

    setAllowListAddress(
      allowListAddress_: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "HubDeployed(address)"(hub?: null): HubDeployedEventFilter;
    HubDeployed(hub?: null): HubDeployedEventFilter;
  };

  estimateGas: {
    autIDAddr(overrides?: CallOverrides): Promise<BigNumber>;

    deployHub(
      market: BigNumberish,
      metadata: string,
      commitment: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getHubByDeployer(
      deployer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHubs(overrides?: CallOverrides): Promise<BigNumber>;

    getTrustedForwarder(overrides?: CallOverrides): Promise<BigNumber>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hubs(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    pluginRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    setAllowListAddress(
      allowListAddress_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    autIDAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deployHub(
      market: BigNumberish,
      metadata: string,
      commitment: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getHubByDeployer(
      deployer: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getHubs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTrustedForwarder(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hubs(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pluginRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setAllowListAddress(
      allowListAddress_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
