/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface NovaFactoryInterface extends utils.Interface {
  functions: {
    "deployNova(address,address,uint256,string,uint256,address)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "deployNova"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployNova",
    values: [string, string, BigNumberish, string, BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "deployNova", data: BytesLike): Result;

  events: {};
}

export interface NovaFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NovaFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployNova(
      deployer: string,
      autIDAddr: string,
      market: BigNumberish,
      metadata: string,
      commitment: BigNumberish,
      pluginRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  deployNova(
    deployer: string,
    autIDAddr: string,
    market: BigNumberish,
    metadata: string,
    commitment: BigNumberish,
    pluginRegistry: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    deployNova(
      deployer: string,
      autIDAddr: string,
      market: BigNumberish,
      metadata: string,
      commitment: BigNumberish,
      pluginRegistry: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    deployNova(
      deployer: string,
      autIDAddr: string,
      market: BigNumberish,
      metadata: string,
      commitment: BigNumberish,
      pluginRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployNova(
      deployer: string,
      autIDAddr: string,
      market: BigNumberish,
      metadata: string,
      commitment: BigNumberish,
      pluginRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
