/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface NovaInterface extends utils.Interface {
  functions: {
    "activateModule(uint256)": FunctionFragment;
    "addAdmin(address)": FunctionFragment;
    "addAdmins(address[])": FunctionFragment;
    "addURL(string)": FunctionFragment;
    "admins(uint256)": FunctionFragment;
    "canJoin(address,uint256)": FunctionFragment;
    "deployer()": FunctionFragment;
    "getAdmins()": FunctionFragment;
    "getAllMembers()": FunctionFragment;
    "getAutIDAddress()": FunctionFragment;
    "getCommitment()": FunctionFragment;
    "getURLs()": FunctionFragment;
    "isAdmin(address)": FunctionFragment;
    "isMember(address)": FunctionFragment;
    "isModuleActivated(uint256)": FunctionFragment;
    "isURLListed(string)": FunctionFragment;
    "join(address,uint256)": FunctionFragment;
    "market()": FunctionFragment;
    "memberCount()": FunctionFragment;
    "members(uint256)": FunctionFragment;
    "metadataUrl()": FunctionFragment;
    "onboardingAddr()": FunctionFragment;
    "pluginRegistry()": FunctionFragment;
    "removeAdmin(address)": FunctionFragment;
    "removeURL(string)": FunctionFragment;
    "setCommitment(uint256)": FunctionFragment;
    "setMetadataUri(string)": FunctionFragment;
    "setOnboardingStrategy(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "activateModule"
      | "addAdmin"
      | "addAdmins"
      | "addURL"
      | "admins"
      | "canJoin"
      | "deployer"
      | "getAdmins"
      | "getAllMembers"
      | "getAutIDAddress"
      | "getCommitment"
      | "getURLs"
      | "isAdmin"
      | "isMember"
      | "isModuleActivated"
      | "isURLListed"
      | "join"
      | "market"
      | "memberCount"
      | "members"
      | "metadataUrl"
      | "onboardingAddr"
      | "pluginRegistry"
      | "removeAdmin"
      | "removeURL"
      | "setCommitment"
      | "setMetadataUri"
      | "setOnboardingStrategy"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activateModule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "addAdmin", values: [string]): string;
  encodeFunctionData(functionFragment: "addAdmins", values: [string[]]): string;
  encodeFunctionData(functionFragment: "addURL", values: [string]): string;
  encodeFunctionData(
    functionFragment: "admins",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canJoin",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deployer", values?: undefined): string;
  encodeFunctionData(functionFragment: "getAdmins", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllMembers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAutIDAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitment",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getURLs", values?: undefined): string;
  encodeFunctionData(functionFragment: "isAdmin", values: [string]): string;
  encodeFunctionData(functionFragment: "isMember", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isModuleActivated",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isURLListed", values: [string]): string;
  encodeFunctionData(
    functionFragment: "join",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "market", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "memberCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "members",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "metadataUrl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onboardingAddr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pluginRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "removeAdmin", values: [string]): string;
  encodeFunctionData(functionFragment: "removeURL", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setCommitment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMetadataUri",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setOnboardingStrategy",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "activateModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addAdmins", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addURL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canJoin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deployer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAdmins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAutIDAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getURLs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isModuleActivated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isURLListed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "join", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "market", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "memberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "metadataUrl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onboardingAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pluginRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removeURL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMetadataUri",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOnboardingStrategy",
    data: BytesLike
  ): Result;

  events: {
    "AdminMemberAdded(address)": EventFragment;
    "AdminMemberRemoved(address)": EventFragment;
    "CommitmentSet()": EventFragment;
    "MarketSet()": EventFragment;
    "MemberAdded()": EventFragment;
    "MetadataUriUpdated()": EventFragment;
    "ModuleActivated(uint256)": EventFragment;
    "UrlAdded(string)": EventFragment;
    "UrlRemoved(string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminMemberAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AdminMemberRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CommitmentSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MarketSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MemberAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MetadataUriUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ModuleActivated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UrlAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UrlRemoved"): EventFragment;
}

export interface AdminMemberAddedEventObject {
  member: string;
}
export type AdminMemberAddedEvent = TypedEvent<
  [string],
  AdminMemberAddedEventObject
>;

export type AdminMemberAddedEventFilter =
  TypedEventFilter<AdminMemberAddedEvent>;

export interface AdminMemberRemovedEventObject {
  member: string;
}
export type AdminMemberRemovedEvent = TypedEvent<
  [string],
  AdminMemberRemovedEventObject
>;

export type AdminMemberRemovedEventFilter =
  TypedEventFilter<AdminMemberRemovedEvent>;

export interface CommitmentSetEventObject {}
export type CommitmentSetEvent = TypedEvent<[], CommitmentSetEventObject>;

export type CommitmentSetEventFilter = TypedEventFilter<CommitmentSetEvent>;

export interface MarketSetEventObject {}
export type MarketSetEvent = TypedEvent<[], MarketSetEventObject>;

export type MarketSetEventFilter = TypedEventFilter<MarketSetEvent>;

export interface MemberAddedEventObject {}
export type MemberAddedEvent = TypedEvent<[], MemberAddedEventObject>;

export type MemberAddedEventFilter = TypedEventFilter<MemberAddedEvent>;

export interface MetadataUriUpdatedEventObject {}
export type MetadataUriUpdatedEvent = TypedEvent<
  [],
  MetadataUriUpdatedEventObject
>;

export type MetadataUriUpdatedEventFilter =
  TypedEventFilter<MetadataUriUpdatedEvent>;

export interface ModuleActivatedEventObject {
  moduleId: BigNumber;
}
export type ModuleActivatedEvent = TypedEvent<
  [BigNumber],
  ModuleActivatedEventObject
>;

export type ModuleActivatedEventFilter = TypedEventFilter<ModuleActivatedEvent>;

export interface UrlAddedEventObject {
  url: string;
}
export type UrlAddedEvent = TypedEvent<[string], UrlAddedEventObject>;

export type UrlAddedEventFilter = TypedEventFilter<UrlAddedEvent>;

export interface UrlRemovedEventObject {
  url: string;
}
export type UrlRemovedEvent = TypedEvent<[string], UrlRemovedEventObject>;

export type UrlRemovedEventFilter = TypedEventFilter<UrlRemovedEvent>;

export interface Nova extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NovaInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    activateModule(
      moduleId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    addAdmin(
      member: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    addAdmins(
      adminAddr: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    addURL(
      url: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    admins(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    canJoin(
      member: string,
      role: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    deployer(overrides?: CallOverrides): Promise<[string]>;

    getAdmins(overrides?: CallOverrides): Promise<[string[]]>;

    getAllMembers(overrides?: CallOverrides): Promise<[string[]]>;

    getAutIDAddress(overrides?: CallOverrides): Promise<[string]>;

    getCommitment(overrides?: CallOverrides): Promise<[BigNumber]>;

    getURLs(overrides?: CallOverrides): Promise<[string[]]>;

    isAdmin(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    isMember(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    isModuleActivated(
      moduleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isURLListed(_url: string, overrides?: CallOverrides): Promise<[boolean]>;

    join(
      newMember: string,
      role: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    market(overrides?: CallOverrides): Promise<[BigNumber]>;

    memberCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    members(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    metadataUrl(overrides?: CallOverrides): Promise<[string]>;

    onboardingAddr(overrides?: CallOverrides): Promise<[string]>;

    pluginRegistry(overrides?: CallOverrides): Promise<[string]>;

    removeAdmin(
      member: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    removeURL(
      url: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setCommitment(
      commitment: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setMetadataUri(
      metadata: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setOnboardingStrategy(
      onboardingPlugin: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  activateModule(
    moduleId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  addAdmin(
    member: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  addAdmins(
    adminAddr: string[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  addURL(
    url: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  admins(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  canJoin(
    member: string,
    role: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  deployer(overrides?: CallOverrides): Promise<string>;

  getAdmins(overrides?: CallOverrides): Promise<string[]>;

  getAllMembers(overrides?: CallOverrides): Promise<string[]>;

  getAutIDAddress(overrides?: CallOverrides): Promise<string>;

  getCommitment(overrides?: CallOverrides): Promise<BigNumber>;

  getURLs(overrides?: CallOverrides): Promise<string[]>;

  isAdmin(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  isMember(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  isModuleActivated(
    moduleId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isURLListed(_url: string, overrides?: CallOverrides): Promise<boolean>;

  join(
    newMember: string,
    role: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  market(overrides?: CallOverrides): Promise<BigNumber>;

  memberCount(overrides?: CallOverrides): Promise<BigNumber>;

  members(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  metadataUrl(overrides?: CallOverrides): Promise<string>;

  onboardingAddr(overrides?: CallOverrides): Promise<string>;

  pluginRegistry(overrides?: CallOverrides): Promise<string>;

  removeAdmin(
    member: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  removeURL(
    url: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setCommitment(
    commitment: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setMetadataUri(
    metadata: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setOnboardingStrategy(
    onboardingPlugin: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    activateModule(
      moduleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    addAdmin(member: string, overrides?: CallOverrides): Promise<void>;

    addAdmins(
      adminAddr: string[],
      overrides?: CallOverrides
    ): Promise<string[]>;

    addURL(url: string, overrides?: CallOverrides): Promise<void>;

    admins(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    canJoin(
      member: string,
      role: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    deployer(overrides?: CallOverrides): Promise<string>;

    getAdmins(overrides?: CallOverrides): Promise<string[]>;

    getAllMembers(overrides?: CallOverrides): Promise<string[]>;

    getAutIDAddress(overrides?: CallOverrides): Promise<string>;

    getCommitment(overrides?: CallOverrides): Promise<BigNumber>;

    getURLs(overrides?: CallOverrides): Promise<string[]>;

    isAdmin(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    isMember(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    isModuleActivated(
      moduleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isURLListed(_url: string, overrides?: CallOverrides): Promise<boolean>;

    join(
      newMember: string,
      role: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    market(overrides?: CallOverrides): Promise<BigNumber>;

    memberCount(overrides?: CallOverrides): Promise<BigNumber>;

    members(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    metadataUrl(overrides?: CallOverrides): Promise<string>;

    onboardingAddr(overrides?: CallOverrides): Promise<string>;

    pluginRegistry(overrides?: CallOverrides): Promise<string>;

    removeAdmin(member: string, overrides?: CallOverrides): Promise<void>;

    removeURL(url: string, overrides?: CallOverrides): Promise<void>;

    setCommitment(
      commitment: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMetadataUri(metadata: string, overrides?: CallOverrides): Promise<void>;

    setOnboardingStrategy(
      onboardingPlugin: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AdminMemberAdded(address)"(member?: null): AdminMemberAddedEventFilter;
    AdminMemberAdded(member?: null): AdminMemberAddedEventFilter;

    "AdminMemberRemoved(address)"(member?: null): AdminMemberRemovedEventFilter;
    AdminMemberRemoved(member?: null): AdminMemberRemovedEventFilter;

    "CommitmentSet()"(): CommitmentSetEventFilter;
    CommitmentSet(): CommitmentSetEventFilter;

    "MarketSet()"(): MarketSetEventFilter;
    MarketSet(): MarketSetEventFilter;

    "MemberAdded()"(): MemberAddedEventFilter;
    MemberAdded(): MemberAddedEventFilter;

    "MetadataUriUpdated()"(): MetadataUriUpdatedEventFilter;
    MetadataUriUpdated(): MetadataUriUpdatedEventFilter;

    "ModuleActivated(uint256)"(moduleId?: null): ModuleActivatedEventFilter;
    ModuleActivated(moduleId?: null): ModuleActivatedEventFilter;

    "UrlAdded(string)"(url?: null): UrlAddedEventFilter;
    UrlAdded(url?: null): UrlAddedEventFilter;

    "UrlRemoved(string)"(url?: null): UrlRemovedEventFilter;
    UrlRemoved(url?: null): UrlRemovedEventFilter;
  };

  estimateGas: {
    activateModule(
      moduleId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    addAdmin(
      member: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    addAdmins(
      adminAddr: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    addURL(
      url: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    admins(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    canJoin(
      member: string,
      role: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deployer(overrides?: CallOverrides): Promise<BigNumber>;

    getAdmins(overrides?: CallOverrides): Promise<BigNumber>;

    getAllMembers(overrides?: CallOverrides): Promise<BigNumber>;

    getAutIDAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getCommitment(overrides?: CallOverrides): Promise<BigNumber>;

    getURLs(overrides?: CallOverrides): Promise<BigNumber>;

    isAdmin(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    isMember(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    isModuleActivated(
      moduleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isURLListed(_url: string, overrides?: CallOverrides): Promise<BigNumber>;

    join(
      newMember: string,
      role: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    market(overrides?: CallOverrides): Promise<BigNumber>;

    memberCount(overrides?: CallOverrides): Promise<BigNumber>;

    members(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    metadataUrl(overrides?: CallOverrides): Promise<BigNumber>;

    onboardingAddr(overrides?: CallOverrides): Promise<BigNumber>;

    pluginRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    removeAdmin(
      member: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    removeURL(
      url: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setCommitment(
      commitment: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setMetadataUri(
      metadata: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setOnboardingStrategy(
      onboardingPlugin: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    activateModule(
      moduleId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    addAdmin(
      member: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    addAdmins(
      adminAddr: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    addURL(
      url: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    admins(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    canJoin(
      member: string,
      role: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deployer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAdmins(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAllMembers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAutIDAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCommitment(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getURLs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isAdmin(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isMember(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isModuleActivated(
      moduleId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isURLListed(
      _url: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    join(
      newMember: string,
      role: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    market(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    memberCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    members(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    metadataUrl(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onboardingAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pluginRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeAdmin(
      member: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    removeURL(
      url: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setCommitment(
      commitment: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setMetadataUri(
      metadata: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setOnboardingStrategy(
      onboardingPlugin: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
