/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  AragonMembershipChecker,
  AragonMembershipCheckerInterface,
} from "../AragonMembershipChecker";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "daoAppAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "member",
        type: "address",
      },
    ],
    name: "isMember",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061029c806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806339ac7a0814610030575b600080fd5b61004361003e3660046101f0565b610057565b604051901515815260200160405180910390f35b60006001600160a01b0383166100b45760405162461bcd60e51b815260206004820152601a60248201527f41757449443a2064616f4170704164647265737320656d70747900000000000060448201526064015b60405180910390fd5b6001600160a01b0382166101005760405162461bcd60e51b815260206004820152601360248201527241757449443a206d656d62657220656d70747960681b60448201526064016100ab565b6000836001600160a01b031663fc0c546a6040518163ffffffff1660e01b8152600401602060405180830381865afa158015610140573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101649190610229565b6040516370a0823160e01b81526001600160a01b03858116600483015291909116906370a0823190602401602060405180830381865afa1580156101ac573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101d0919061024d565b119392505050565b6001600160a01b03811681146101ed57600080fd5b50565b6000806040838503121561020357600080fd5b823561020e816101d8565b9150602083013561021e816101d8565b809150509250929050565b60006020828403121561023b57600080fd5b8151610246816101d8565b9392505050565b60006020828403121561025f57600080fd5b505191905056fea264697066735822122055ac81ca74e35a65fc86a37c63d142c5f3f6d634df1fc1be76e3982733c757fc64736f6c63430008130033";

type AragonMembershipCheckerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AragonMembershipCheckerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AragonMembershipChecker__factory extends ContractFactory {
  constructor(...args: AragonMembershipCheckerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string }
  ): Promise<AragonMembershipChecker> {
    return super.deploy(overrides || {}) as Promise<AragonMembershipChecker>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): AragonMembershipChecker {
    return super.attach(address) as AragonMembershipChecker;
  }
  override connect(signer: Signer): AragonMembershipChecker__factory {
    return super.connect(signer) as AragonMembershipChecker__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AragonMembershipCheckerInterface {
    return new utils.Interface(_abi) as AragonMembershipCheckerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AragonMembershipChecker {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AragonMembershipChecker;
  }
}
