/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { AutIDAddress, AutIDAddressInterface } from "../AutIDAddress";

const _abi = [
  {
    inputs: [],
    name: "getAutIDAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class AutIDAddress__factory {
  static readonly abi = _abi;
  static createInterface(): AutIDAddressInterface {
    return new utils.Interface(_abi) as AutIDAddressInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AutIDAddress {
    return new Contract(address, _abi, signerOrProvider) as AutIDAddress;
  }
}
