/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { DAOCommitment, DAOCommitmentInterface } from "../DAOCommitment";

const _abi = [
  {
    anonymous: false,
    inputs: [],
    name: "CommitmentSet",
    type: "event",
  },
  {
    inputs: [],
    name: "getCommitment",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class DAOCommitment__factory {
  static readonly abi = _abi;
  static createInterface(): DAOCommitmentInterface {
    return new utils.Interface(_abi) as DAOCommitmentInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DAOCommitment {
    return new Contract(address, _abi, signerOrProvider) as DAOCommitment;
  }
}
