/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDAOMetadataSet,
  IDAOMetadataSetInterface,
} from "../IDAOMetadataSet";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "metadata",
        type: "string",
      },
    ],
    name: "setMetadataUri",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDAOMetadataSet__factory {
  static readonly abi = _abi;
  static createInterface(): IDAOMetadataSetInterface {
    return new utils.Interface(_abi) as IDAOMetadataSetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDAOMetadataSet {
    return new Contract(address, _abi, signerOrProvider) as IDAOMetadataSet;
  }
}
