/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDAOMembershipSet,
  IDAOMembershipSetInterface,
} from "../IDAOMembershipSet";

const _abi = [
  {
    anonymous: false,
    inputs: [],
    name: "MemberAdded",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newMember",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "role",
        type: "uint256",
      },
    ],
    name: "join",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDAOMembershipSet__factory {
  static readonly abi = _abi;
  static createInterface(): IDAOMembershipSetInterface {
    return new utils.Interface(_abi) as IDAOMembershipSetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDAOMembershipSet {
    return new Contract(address, _abi, signerOrProvider) as IDAOMembershipSet;
  }
}
