/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDAOExpanderData,
  IDAOExpanderDataInterface,
} from "../IDAOExpanderData";

const _abi = [
  {
    anonymous: false,
    inputs: [],
    name: "DiscordServerSet",
    type: "event",
  },
  {
    inputs: [],
    name: "getDAOData",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "contractType",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "daoAddress",
            type: "address",
          },
        ],
        internalType: "struct IDAOExpanderData.DAOExpanssionData",
        name: "data",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDAOExpanderData__factory {
  static readonly abi = _abi;
  static createInterface(): IDAOExpanderDataInterface {
    return new utils.Interface(_abi) as IDAOExpanderDataInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDAOExpanderData {
    return new Contract(address, _abi, signerOrProvider) as IDAOExpanderData;
  }
}
