/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IDAOURL, IDAOURLInterface } from "../IDAOURL";

const _abi = [
  {
    inputs: [],
    name: "getURLs",
    outputs: [
      {
        internalType: "string[]",
        name: "",
        type: "string[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_url",
        type: "string",
      },
    ],
    name: "isURLListed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDAOURL__factory {
  static readonly abi = _abi;
  static createInterface(): IDAOURLInterface {
    return new utils.Interface(_abi) as IDAOURLInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDAOURL {
    return new Contract(address, _abi, signerOrProvider) as IDAOURL;
  }
}
