/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IDAOAdmin, IDAOAdminInterface } from "../IDAOAdmin";

const _abi = [
  {
    inputs: [],
    name: "getAdmins",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "member",
        type: "address",
      },
    ],
    name: "isAdmin",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDAOAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): IDAOAdminInterface {
    return new utils.Interface(_abi) as IDAOAdminInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDAOAdmin {
    return new Contract(address, _abi, signerOrProvider) as IDAOAdmin;
  }
}
