/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMembershipChecker,
  IMembershipCheckerInterface,
} from "../IMembershipChecker";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "daoAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "member",
        type: "address",
      },
    ],
    name: "isMember",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMembershipChecker__factory {
  static readonly abi = _abi;
  static createInterface(): IMembershipCheckerInterface {
    return new utils.Interface(_abi) as IMembershipCheckerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMembershipChecker {
    return new Contract(address, _abi, signerOrProvider) as IMembershipChecker;
  }
}
