/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IModule, IModuleInterface } from "../IModule";

const _abi = [
  {
    inputs: [],
    name: "FunctionNotImplemented",
    type: "error",
  },
  {
    inputs: [],
    name: "isActive",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "moduleId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "hubAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IModule__factory {
  static readonly abi = _abi;
  static createInterface(): IModuleInterface {
    return new utils.Interface(_abi) as IModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IModule {
    return new Contract(address, _abi, signerOrProvider) as IModule;
  }
}
