/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ISWLegacyDAO, ISWLegacyDAOInterface } from "../ISWLegacyDAO";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "member",
        type: "address",
      },
    ],
    name: "isMember",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISWLegacyDAO__factory {
  static readonly abi = _abi;
  static createInterface(): ISWLegacyDAOInterface {
    return new utils.Interface(_abi) as ISWLegacyDAOInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISWLegacyDAO {
    return new Contract(address, _abi, signerOrProvider) as ISWLegacyDAO;
  }
}
