/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MolochV1MembershipChecker,
  MolochV1MembershipCheckerInterface,
} from "../MolochV1MembershipChecker";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "daoAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "member",
        type: "address",
      },
    ],
    name: "isMember",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102b5806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806339ac7a0814610030575b600080fd5b61004361003e366004610192565b610057565b604051901515815260200160405180910390f35b60006001600160a01b0383166100b45760405162461bcd60e51b815260206004820152601760248201527f41757449443a2064616f4164647265737320656d70747900000000000000000060448201526064015b60405180910390fd5b6001600160a01b0382166101005760405162461bcd60e51b815260206004820152601360248201527241757449443a206d656d62657220656d70747960681b60448201526064016100ab565b60405163022b92c360e21b81526001600160a01b038381166004830152600091908516906308ae4b0c9060240160c060405180830381865afa15801561014a573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061016e91906101eb565b60200151119392505050565b6001600160a01b038116811461018f57600080fd5b50565b600080604083850312156101a557600080fd5b82356101b08161017a565b915060208301356101c08161017a565b809150509250929050565b80516101d68161017a565b919050565b805180151581146101d657600080fd5b600060c082840312156101fd57600080fd5b60405160c0810181811067ffffffffffffffff8211171561022e57634e487b7160e01b600052604160045260246000fd5b60405261023a836101cb565b8152602083015160208201526040830151604082015261025c606084016101db565b60608201526080830151608082015260a083015160a0820152809150509291505056fea264697066735822122078d91b31a0137958eaf3e1bb434a52a02cfea650a918fa676d75b27027273db064736f6c63430008130033";

type MolochV1MembershipCheckerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MolochV1MembershipCheckerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MolochV1MembershipChecker__factory extends ContractFactory {
  constructor(...args: MolochV1MembershipCheckerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string }
  ): Promise<MolochV1MembershipChecker> {
    return super.deploy(overrides || {}) as Promise<MolochV1MembershipChecker>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MolochV1MembershipChecker {
    return super.attach(address) as MolochV1MembershipChecker;
  }
  override connect(signer: Signer): MolochV1MembershipChecker__factory {
    return super.connect(signer) as MolochV1MembershipChecker__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MolochV1MembershipCheckerInterface {
    return new utils.Interface(_abi) as MolochV1MembershipCheckerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MolochV1MembershipChecker {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MolochV1MembershipChecker;
  }
}
