/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  AragonVotingApp,
  AragonVotingAppInterface,
} from "../../Aragon.sol/AragonVotingApp";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token_",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "token",
    outputs: [
      {
        internalType: "contract IMiniMeToken",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161012338038061012383398101604081905261002f91610054565b600080546001600160a01b0319166001600160a01b0392909216919091179055610084565b60006020828403121561006657600080fd5b81516001600160a01b038116811461007d57600080fd5b9392505050565b6091806100926000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063fc0c546a14602d575b600080fd5b600054603f906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f3fea264697066735822122086aceddd08933968fafcf8b14bc924ae82cafba3fa077a338acf33356f934a7e64736f6c63430008130033";

type AragonVotingAppConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AragonVotingAppConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AragonVotingApp__factory extends ContractFactory {
  constructor(...args: AragonVotingAppConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    token_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<AragonVotingApp> {
    return super.deploy(token_, overrides || {}) as Promise<AragonVotingApp>;
  }
  override getDeployTransaction(
    token_: string,
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(token_, overrides || {});
  }
  override attach(address: string): AragonVotingApp {
    return super.attach(address) as AragonVotingApp;
  }
  override connect(signer: Signer): AragonVotingApp__factory {
    return super.connect(signer) as AragonVotingApp__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AragonVotingAppInterface {
    return new utils.Interface(_abi) as AragonVotingAppInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AragonVotingApp {
    return new Contract(address, _abi, signerOrProvider) as AragonVotingApp;
  }
}
