/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAragonApp__factory } from "./IAragonApp__factory";
export { IMiniMeToken__factory } from "./IMiniMeToken__factory";
