name: build & test & deploy contracts on mumbai network
on:
  push:
    branches:
      - master
env:
  CHAIN_ID: "80001"

jobs:
  deploy-mumbai:
    runs-on: ubuntu:20.04
    env:
      PVK_A1: ${{ secrets.mumbai_deployer_pk }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 18.17
      
      - name: build node modules
        run: yarn install --non-interactive 

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: build contracts
        run: forge build

      - name: test contracts
        run: forge test

      - name: deploy contracts to mumbai
        run: forge script ./script/DeployAll.s.sol --rpc-url ${{ secrets.mumbai_rpc_url }} \
              --etherscan-api-key ${{ secrets.polygonscan_api_key }} \
              --private-key $PVK_A1 \
              --broadcast \
              --verify
