name: wip-dev-ci

env:
  FOUNDRY_PROFILE: "ci"

on:
  push:
    branches:
      - test-dev-2
      - dev-main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.1

      - name: Install dependencies
        run: npm install

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"


      - name: Run Forge tests
        run: forge t

      # - name: Build with Hardhat
      #   run: npm run test

      # - name: generate types
      #   run: npx typechain --target ethers-v5  './out/*.sol/*'

      # - name: Commit changes
      #   run: |
      #     git config --local user.email "actions@github.com"
      #     git config --local user.name "GitHub Actions"
      #     git add .
      #     git commit -m "ci: forge test"
      #     git push
